"""Bounded tools that an Adapt Agent may execute without a Canonical Operation wrapper."""

from rolo.agent_tools.broker import NativeToolBroker, native_broker_request
from rolo.agent_tools.native_tools import (
    AgentNativeRunner,
    AgentNativeToolDescriptor,
    AgentNativeToolResult,
    NativeToolInvocation,
    NativeToolParameter,
    NativeToolStatus,
    RemoteAgentNativeRunner,
    default_agent_native_catalog,
    load_agent_native_catalog,
    native_operation_family_map,
    native_variant_aliases,
    reduced_agent_native_catalog,
)
from rolo.agent_tools.planning import (
    ToolPlan,
    ToolPlanningRequest,
    ToolPlanStep,
    build_tool_plan,
    validate_tool_plan,
)
from rolo.agent_tools.rollout import (
    NativeToolCanaryGateReport,
    NativeToolExecutionParity,
    NativeToolParityReport,
    NativeToolRolloutDecision,
    NativeToolRunSummary,
    build_native_operation_parity_report,
    compare_native_to_direct,
    decide_native_tool_rollout,
    evaluate_native_tool_canary_gate,
    summarize_native_tool_run,
)
from rolo.agent_tools.session import (
    NativeToolSession,
    NativeToolSessionAuthorizationError,
    NativeToolSessionBudget,
    NativeToolSessionBudgetError,
    NativeToolSessionDescriptor,
    native_catalog_sha256,
)
from rolo.agent_tools.session_factory import create_profile_native_tool_session

__all__ = [
    "AgentNativeRunner",
    "RemoteAgentNativeRunner",
    "AgentNativeToolDescriptor",
    "AgentNativeToolResult",
    "NativeToolStatus",
    "NativeToolInvocation",
    "NativeToolParameter",
    "default_agent_native_catalog",
    "load_agent_native_catalog",
    "native_operation_family_map",
    "native_variant_aliases",
    "reduced_agent_native_catalog",
    "ToolPlan",
    "ToolPlanningRequest",
    "ToolPlanStep",
    "build_tool_plan",
    "validate_tool_plan",
    "NativeToolSession",
    "NativeToolSessionAuthorizationError",
    "NativeToolSessionBudget",
    "NativeToolSessionBudgetError",
    "NativeToolSessionDescriptor",
    "native_catalog_sha256",
    "create_profile_native_tool_session",
    "NativeToolBroker",
    "native_broker_request",
    "NativeToolRolloutDecision",
    "NativeToolRunSummary",
    "NativeToolParityReport",
    "NativeToolExecutionParity",
    "NativeToolCanaryGateReport",
    "build_native_operation_parity_report",
    "compare_native_to_direct",
    "decide_native_tool_rollout",
    "evaluate_native_tool_canary_gate",
    "summarize_native_tool_run",
]
